import img from "../assets/img/img3.jpg";
import img2 from '../assets/img/img2.jpg';
import img3 from '../assets/img/img1.jpg';

export const list = [
	{
		id: 1,
		img: img2,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "new",
	},
	{
		id: 2,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "new",
	},
	{
		id: 3,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "new",
	},
	{
		id: 4,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "new",
	},
	{
		id: 5,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "new",
	},
	{
		id: 6,
		img: img3,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "old",
	},
	{
		id: 7,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "old",
	},
	{
		id: 8,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "old",
	},
	{
		id: 9,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
		category: "old",
	},
	{
		id: 10,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
	},
	{
		id: 11,
		img: img,
		text1: "title one",
		para: "7.5k stars",
		btn: "5.6k stars",
		text2: "67k stars",
		para1: "86k stars",
		btn1: "567(0%)",
		sale: "55",
		outOf: "/999",
	},
];

export const column = [
	{
		id: 1,
	},
	{ collection: "Collection" },
	{ floor: "Floor Price" },
	{ best: "Best Offer" },
	{ hor: "24H Vol" },
	{ dvol: "7D Vol" },
	{ owner: "Owners" },
	{ sale: "For Sale" },
];
