import img from "../assets/img/img1.jpg";

export const items = [
	{
		id: 1,
		text1: "MYSTICFIGURE#01",
		author: "Nft name another title",
		para: "Toalyg",
		btn: "Place a bid",
		text2: "1.00ETH",
		para1: "$3,618.36",
		btn1: "View Artwork",
		img: img,
	},
	{
		id: 2,
		text1: "MYSTICFIGURE#01",
		author: "Nft name another title",
		para: "Toalyg",
		btn: "Place a bid",
		text2: "1.00ETH",
		para1: "$3,618.36",
		btn1: "View Artwork",
		img: img,
	},
	{
		id: 3,
		text1: "MYSTICFIGURE#01",
		author: "Nft name another title",
		para: "Toalyg",
		btn: "Place a bid",
		text2: "1.00ETH",
		para1: "$3,618.36",
		btn1: "View Artwork",
		img: img,
	},
	{
		id: 4,
		text1: "MYSTICFIGURE#01",
		author: "Nft name another title",
		para: "Toalyg",
		btn: "Place a bid",
		text2: "1.00ETH",
		para1: "$3,618.36",
		btn1: "View Artwork",
		img: img,
	},
	{
		id: 5,
		text1: "MYSTICFIGURE#01",
		author: "Nft name another title",
		para: "Toalyg",
		btn: "Place a bid",
		text2: "1.00ETH",
		para1: "$3,618.36",
		btn1: "View Artwork",
		img: img,
	},
	{
		id: 6,
		text1: "MYSTICFIGURE#01",
		author: "Nft name another title",
		para: "Toalyg",
		btn: "Place a bid",
		text2: "1.00ETH",
		para1: "$3,618.36",
		btn1: "View Artwork",
		img: img,
	},
];

// {id: 6,
// 		image: img,
// 		title: "Nft name another title",
// 		year: "2017",}

export const collection = [
	{
		id: 1,
		image: img,
		title: "Nft name another title",
		year: "2017",
	},
	{
		id: 2,
		image: img,
		title: "Nft name another title",
		year: "2017",
	},
	{
		id: 3,
		image: img,
		title: "Nft name another title",
		year: "2017",
	},
	{
		id: 4,
		image: img,
		title: "Nft name another title",
		year: "2017",
	},
	{
		id: 5,
		image: img,
		title: "Nft name another title",
		year: "2017",
	},
	{
		id: 6,
		image: img,
		title: "Nft name another title",
		year: "2017",
	},
];
